### ISSUE TITLE
Blur documentation must be clearer about 14393 requirement and must also mention AnimationExtensions.IsBlurSupported

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/UWPCommunityToolkit-docs#29]

**Comment by jasonshortphd** [comment]
I will add this

**Comment by jasonshortphd** [comment]
There is a formatting error in the XML docs where the entry says prior to call **Blur/>**.  We need to remove that closing tag.

        <member name="P:Microsoft.Toolkit.Uwp.UI.Animations.AnimationExtensions.IsBlurSupported">
            <summary>
            Gets a value indicating whether the platform supports blur.
            </summary>
            <remarks>
            A check should always be made to IsBlurSupported prior to calling **Blur/>**,
            since older operating systems will not support blurs.
            </remarks>

**Comment by jasonshortphd** [comment]
Added NOTE: at the top of the file, and a link to the extensions for IsBlurSupports

**Comment by deltakosh** [comment]
xml docs fixed
