### ISSUE TITLE
Lost link in UWPCommunityToolkit-docs/en-us/services.md

### ISSUE THREAD

**Issue by lindexi** [Microsoft/UWPCommunityToolkit-docs#42]
The link `getting Started with the UWP Community Toolkit` (https://github.com/Microsoft/UWPCommunityToolkit-docs/blob/master/en-us/%7B%7Bsite.baseurl%7D%7D/%7B%7Bpage.lang%7D%7D/getting-started.htm) is error in https://github.com/Microsoft/UWPCommunityToolkit-docs/blob/master/en-us/services.md

And the link should be https://github.com/Microsoft/UWPCommunityToolkit-docs/blob/master/en-us/getting-started.md

**Comment by jasonshortphd** [comment]
Thank you

**Comment by jasonshortphd** [comment]
I think this might be an issue just because we are not publishing this to main yet, but it is working on our internal preview server.  This will be published in the next couple days.  Thanks for the issue.
