### ISSUE TITLE
Links back to GitHub on readthedocs aren't working

### ISSUE THREAD

**Issue by bartlannoeye** [Microsoft/UWPCommunityToolkit-docs#46]
Both links return 404's on GitHub. I suppose this is a setting somewhere, as I can't find the "Edit" word in this repository.

![image](https://cloud.githubusercontent.com/assets/5115577/19029187/459e1006-8944-11e6-95fc-07d90387e2f5.png)

**Comment by jasonshortphd** [comment]
This repo is not the current docs.  The current docs are on the main repo \docs\ directory.

This repo is closing down starting today.
